import { test, expect, type Page } from '@playwright/test';
import { ACTIVITIES, PRINCESS_IDS, RECIPES, ROOM_WIDTH, STATIONS, roomIndex } from '../src/features/games/princess-mansion/data';
import { advance, command } from '../src/features/games/princess-mansion/model';
import { BACKUP_KEY, SAVE_KEY } from '../src/features/games/princess-mansion/persistence';
import { audioState, careFixture, failSaveWrites, readyMansion, savedMansion, seedMansion, seedRawMansion, trackAudio, worldPoint } from './princess-mansion-fixtures';
import legacy from './fixtures/princess-mansion-legacy.json';
import en from '../messages/en.json';
import he from '../messages/he.json';
import zh from '../messages/zh.json';
import es from '../messages/es.json';

test.describe.configure({ mode: 'parallel' });

async function rendered(page: Page, world?: string): Promise<void> {
  await expect(page.getByTestId('mansion-game')).toHaveAttribute('data-ready', 'true');
  if (world) await expect(page.locator('canvas')).toHaveAttribute('data-world', world);
  await expect(page.locator('canvas')).toHaveCount(1);
}

test('a mall outing freezes the home princess, excludes her hit target, and shares a visibly worn purchase', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1280, height: 900 });
  let state = careFixture();
  state.hearts = 10;
  state.coins = 60;
  state.autonomyEnabled = false;
  state = command(state, { type: 'invite', id: 'mira' }).state;
  state = command(state, { type: 'place', id: 'mira', room: 'basement', x: 320, y: 480, stationId: 'cauldron-left' }).state;
  state = command(state, { type: 'select', id: 'liora' }).state;
  await seedMansion(page, state);
  await readyMansion(page);
  await page.getByRole('button', { name: 'Outings', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Liora', exact: true })).toBeChecked();
  await expect(page.getByRole('checkbox', { name: 'Mira', exact: true })).not.toBeChecked();
  await page.getByRole('button', { name: "Let's go!", exact: true }).click();
  await rendered(page, 'mall');
  const departed = await savedMansion(page);
  const home = departed.princesses.find(princess => princess.id === 'mira');
  expect(departed.trip?.companions).toEqual(['liora']);
  await expect(page.getByRole('button', { name: 'Mira', exact: true })).toBeDisabled();
  const counter = await worldPoint(page, 320, 390);
  await page.mouse.click(counter.x, counter.y);
  const boutique = page.getByRole('dialog', { name: 'The royal boutique' });
  await expect(boutique).toBeVisible();
  const dress = page.getByTestId('item-rose-gala');
  await dress.getByRole('button', { name: 'Try a look', exact: true }).click();
  await expect(page.getByTestId('shop-preview').locator('img')).toHaveAttribute('src', /liora-rose-gala-portrait\.svg$/);
  expect((await savedMansion(page)).coins).toBe(60);
  expect((await savedMansion(page)).princesses[0].outfit).toBe('original');
  await dress.getByRole('button', { name: 'Buy · 18 coins', exact: true }).click();
  expect((await savedMansion(page)).inventory.outfits).toEqual(['rose-gala']);
  expect((await savedMansion(page)).coins).toBe(42);
  await dress.getByRole('button', { name: 'Wear', exact: true }).click();
  await rendered(page, 'mall');
  await expect(page.getByRole('button', { name: 'Liora', exact: true }).locator('img').first()).toHaveAttribute('src', /liora-rose-gala-portrait\.svg$/);
  await page.screenshot({ path: testInfo.outputPath('equipped-boutique.png') });
  await page.reload();
  await rendered(page, 'mall');
  const restored = await savedMansion(page);
  expect(restored.princesses[0].outfit).toBe('rose-gala');
  expect(restored.coins).toBe(42);
  expect(restored.princesses.find(princess => princess.id === 'mira')).toEqual(home);
  expect(restored.destinationClocks.home).toBe(departed.destinationClocks.home);
  expect(restored.hearts).toBe(10);
  await page.getByRole('button', { name: 'Return home', exact: true }).click();
  await rendered(page, 'mansion');
  await page.getByRole('button', { name: 'Mira', exact: true }).click();
  await rendered(page, 'basement');
  await page.getByRole('button', { name: 'Our royal wardrobe', exact: true }).click();
  await page.getByTestId('collection-rose-gala').getByRole('button', { name: 'Wear', exact: true }).click();
  await rendered(page, 'basement');
  expect((await savedMansion(page)).princesses.find(princess => princess.id === 'mira')?.outfit).toBe('rose-gala');
  expect((await savedMansion(page)).coins).toBe(42);
});

test('toys are permanent, playable at home, and fullness preserves a purchased cone across reload', async ({ page }, testInfo) => {
  const state = careFixture('boutique');
  state.coins = 60;
  state.autonomyEnabled = false;
  state.princesses[0].needs.satiety = 100;
  await seedMansion(page, state);
  await readyMansion(page);
  await page.getByTestId('room-toyshop').click();
  await page.getByTestId('shop-toys').click();
  const dragon = page.getByTestId('item-plush-dragon');
  await dragon.getByRole('button', { name: 'Play a free demo', exact: true }).click();
  expect((await savedMansion(page)).inventory.toys).toEqual([]);
  await dragon.getByRole('button', { name: 'Buy · 10 coins', exact: true }).click();
  await dragon.getByRole('button', { name: 'Choose toy', exact: true }).click();
  expect((await savedMansion(page)).princesses[0].toy).toBe('plush-dragon');
  await page.getByTestId('room-icecream').click();
  await page.getByTestId('shop-treats').click();
  const strawberry = page.getByTestId('item-strawberry');
  await strawberry.getByRole('button', { name: 'Buy · 4 coins', exact: true }).click();
  await strawberry.getByRole('button', { name: 'Serve one', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'A scoop of happiness' })).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('status')).toContainText('Not now');
  expect((await savedMansion(page)).inventory.treats.strawberry).toBe(1);
  expect((await savedMansion(page)).coins).toBe(46);
  await page.reload();
  await rendered(page, 'mall');
  expect((await savedMansion(page)).inventory.toys).toEqual(['plush-dragon']);
  expect((await savedMansion(page)).inventory.treats.strawberry).toBe(1);
  await page.getByRole('button', { name: 'Return home', exact: true }).click();
  await rendered(page, 'mansion');
  await page.getByTestId('room-games').click();
  await page.getByTestId('station-toy-castle').click();
  await expect.poll(async () => (await savedMansion(page)).princesses[0].activity?.stationId).toBe('toy-castle');
  expect((await savedMansion(page)).princesses[0].toy).toBe('plush-dragon');
  await page.screenshot({ path: testInfo.outputPath('cuddle-dragon-play.png') });
});

test('accepted portable ice cream is consumed exactly once and restores food without buying rewards', async ({ page }, testInfo) => {
  const state = careFixture('beach');
  state.autonomyEnabled = false;
  state.inventory.treats.blueberry = 2;
  state.coins = 20;
  await seedMansion(page, state);
  await readyMansion(page);
  await page.getByRole('button', { name: 'Our picnic bag', exact: true }).click();
  await page.getByTestId('collection-blueberry').getByRole('button', { name: 'Serve one', exact: true }).click();
  const served = await savedMansion(page);
  expect(served.inventory.treats.blueberry).toBe(1);
  expect(served.princesses[0].activity).toMatchObject({ activityId: 'icecream', stationId: null, consumedTreatId: 'blueberry', rewardEligible: false });
  await page.screenshot({ path: testInfo.outputPath('beach-icecream.png') });
  await page.reload();
  await rendered(page, 'beach');
  await expect.poll(async () => (await savedMansion(page)).princesses[0].activity, { timeout: 9000 }).toBeNull();
  const finished = await savedMansion(page);
  expect(finished.inventory.treats.blueberry).toBe(1);
  expect(finished.coins).toBe(20);
  expect(finished.hearts).toBe(0);
  expect(finished.princesses[0].needs.satiety).toBeGreaterThan(84);
});

for (const stationId of ['royal-slide', 'storybook-treehouse', 'sandcastle-cove', 'shell-collection', 'shallow-splash']) {
  test(`${stationId} welcomes full Fun, preserves a high meter, and gives no completion reward`, async ({ page }, testInfo) => {
    const station = STATIONS.find(item => item.id === stationId);
    if (!station) throw new Error(`Missing expansion attraction ${stationId}`);
    const state = careFixture(station.room);
    state.autonomyEnabled = false;
    state.princesses[0].needs.fun = 100;
    state.princesses[0].poutUntil = 2300;
    await seedMansion(page, state);
    await readyMansion(page);
    await page.getByTestId(`station-${stationId}`).click();
    const active = await savedMansion(page);
    expect(active.princesses[0].activity).toMatchObject({ activityId: station.activity, rewardEligible: false });
    expect(active.princesses[0].poutUntil).toBe(0);
    await page.waitForTimeout(4100);
    await expect(page.getByRole('progressbar', { name: 'Fun', exact: true })).toHaveAttribute('aria-valuenow', '100');
    await page.screenshot({ path: testInfo.outputPath(`${stationId}-in-motion.png`) });
    await page.reload();
    await rendered(page);
    await expect.poll(async () => (await savedMansion(page)).princesses[0].activity, { timeout: ACTIVITIES[station.activity].duration + 4000 }).toBeNull();
    const completed = await savedMansion(page);
    expect(completed.hearts).toBe(0);
    expect(completed.coins).toBe(10);
    expect(completed.princesses[0].needs.fun).toBeGreaterThan(98);
    expect(completed.princesses[0].happiness - state.princesses[0].happiness).toBeLessThan(1);
  });
}

test('potion ingredients hold only the lesson, wrong choices are hints, and recipe steps survive reload', async ({ page }, testInfo) => {
  const state = careFixture('basement');
  state.autonomyEnabled = false;
  await seedMansion(page, state);
  await readyMansion(page);
  await page.getByTestId('station-cauldron-left').click();
  const panel = page.getByTestId('potion-lesson');
  await expect(panel).toHaveAttribute('data-stage', 'ingredients');
  await expect.poll(async () => Number(await page.getByTestId('mansion-game').getAttribute('data-active-time'))).toBeGreaterThan(1000);
  await page.getByTestId('ingredient-stardust').click();
  await expect(page.getByText('Almost! This recipe wants Moonbeam water next.')).toBeVisible();
  expect((await savedMansion(page)).princesses[0].activity).toMatchObject({ elapsed: 0, potion: { ingredients: [] } });
  await page.getByTestId('recipe-blossom').click();
  await page.getByTestId('ingredient-dewdrop').click();
  await page.reload();
  await rendered(page, 'basement');
  await expect(page.getByTestId('recipe-blossom')).toHaveAttribute('aria-pressed', 'true');
  expect((await savedMansion(page)).princesses[0].activity).toMatchObject({ potion: { recipe: 'blossom', ingredients: ['dewdrop'] } });
  for (const ingredient of RECIPES.blossom.ingredients.slice(1)) await page.getByTestId(`ingredient-${ingredient}`).click();
  await expect(panel).toHaveAttribute('data-stage', 'mixing');
  await expect(page.getByTestId('recipe-starlight')).toHaveCount(0);
  await expect(page.getByTestId('ingredient-dewdrop')).toHaveCount(0);
  await expect(page.locator('canvas')).toBeFocused();
  const canvas = await page.locator('canvas').boundingBox();
  const header = await page.locator('header').boundingBox();
  const viewport = page.viewportSize();
  if (!canvas || !header || !viewport) throw new Error('Expected the visible potion world and game header');
  expect(canvas.y).toBeGreaterThanOrEqual(header.y + header.height);
  expect(canvas.y + canvas.height).toBeLessThanOrEqual(viewport.height);
  await expect(panel).toHaveAttribute('data-stage', 'reveal', { timeout: 14000 });
  await page.screenshot({ path: testInfo.outputPath('blossom-reveal.png') });
  await expect.poll(async () => (await savedMansion(page)).hearts, { timeout: 6000 }).toBe(1);
  expect((await savedMansion(page)).coins).toBe(13);
});

test('automatic basement lessons finish without ingredient input', async ({ page }) => {
  const state = careFixture('basement');
  state.activeTime = 60000;
  state.destinationClocks.home = 60000;
  state.princesses[0].needs.energy = 80;
  state.princesses[0].autonomy.nextDecisionAt = 0;
  await seedMansion(page, state);
  await readyMansion(page);
  await expect.poll(async () => (await savedMansion(page)).princesses[0].activity?.source, { timeout: 10000 }).toBe('princess');
  await expect(page.getByTestId('potion-lesson')).toHaveCount(0);
  await expect.poll(async () => (await savedMansion(page)).hearts, { timeout: 18000 }).toBe(1);
  expect((await savedMansion(page)).coins).toBe(13);
});

test('carrying, WASD and floor controls can move a princess into the basement in one canvas', async ({ page }) => {
  await seedMansion(page, careFixture());
  await readyMansion(page);
  await page.getByRole('button', { name: 'Move princess', exact: true }).click();
  await page.getByTestId('floor-basement').click();
  await rendered(page, 'basement');
  await expect(page.getByTestId('mansion-game')).toHaveAttribute('data-moving', 'true');
  expect((await savedMansion(page)).princesses[0].room).toBe('basement');
  await page.locator('canvas').focus();
  for (let i = 0; i < 9; i++) await page.keyboard.press('a');
  await page.keyboard.press('Enter');
  await expect.poll(async () => (await savedMansion(page)).princesses[0].activity?.stationId).toBe('cauldron-left');
  await expect(page.getByTestId('potion-lesson')).toBeVisible();
  await expect(page.locator('canvas')).toHaveCount(1);
});

test('a pointer-held princess keeps her grab point when floor navigation changes the camera geometry', async ({ page }) => {
  const state = careFixture();
  state.autonomyEnabled = false;
  await seedMansion(page, state);
  await readyMansion(page);
  const princess = state.princesses[0];
  const start = await worldPoint(page, roomIndex(princess.room) * ROOM_WIDTH + princess.x, princess.y - 78);
  await page.mouse.move(start.x, start.y);
  await page.mouse.down();
  await page.mouse.move(start.x + 14, start.y, { steps: 3 });
  await expect(page.getByTestId('mansion-game')).toHaveAttribute('data-moving', 'true');
  await page.keyboard.press('Shift+Tab');
  await expect(page.getByRole('button', { name: 'Outings', exact: true })).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  await expect(page.getByTestId('floor-basement')).toBeFocused();
  await page.keyboard.press('Enter');
  await rendered(page, 'basement');
  await expect(page.getByTestId('mansion-game')).toHaveAttribute('data-moving', 'true');
  const target = await worldPoint(page, 335, 440);
  await page.mouse.move(target.x, target.y, { steps: 8 });
  await page.mouse.up();
  await expect.poll(async () => (await savedMansion(page)).princesses[0].activity?.stationId).toBe('cauldron-left');
  await expect(page.getByTestId('potion-lesson')).toBeVisible();
});

test('purchase write failures preserve the old candidate and never replay on retry', async ({ page }) => {
  const state = careFixture('boutique');
  state.coins = 50;
  state.autonomyEnabled = false;
  await seedMansion(page, state);
  await readyMansion(page);
  await page.getByTestId('shop-outfits').click();
  await failSaveWrites(page);
  await page.getByTestId('item-rose-gala').getByRole('button', { name: 'Buy · 18 coins', exact: true }).click();
  await expect(page.getByRole('dialog', { name: "Let's protect your adventure" })).toContainText('previous save is safe');
  expect((await savedMansion(page)).coins).toBe(50);
  expect((await savedMansion(page)).inventory.outfits).toEqual([]);
  await expect(page.getByTestId('mansion-game')).toHaveAttribute('data-coins', '50');
  await page.evaluate(() => localStorage.setItem('mansion-simulate-quota', 'false'));
  await page.getByRole('button', { name: 'Try saving again', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'The royal boutique' })).toBeVisible();
  expect((await savedMansion(page)).coins).toBe(50);
  expect((await savedMansion(page)).inventory.outfits).toEqual([]);
  await page.getByTestId('item-rose-gala').getByRole('button', { name: 'Buy · 18 coins', exact: true }).click();
  expect((await savedMansion(page)).coins).toBe(32);
  expect((await savedMansion(page)).inventory.outfits).toEqual(['rose-gala']);
});

test('an authentic version-1 meal renders, migrates with its raw backup, and completes only once', async ({ page }) => {
  const raw = JSON.stringify(legacy.schema1);
  await seedRawMansion(page, raw);
  await readyMansion(page);
  expect(await page.evaluate(key => localStorage.getItem(key), SAVE_KEY)).toBe(raw);
  await page.getByRole('button', { name: /Got it! Let's Play!/ }).click();
  expect(await page.evaluate(key => localStorage.getItem(key), BACKUP_KEY)).toBe(raw);
  const migrated = await savedMansion(page);
  expect(migrated.schemaVersion).toBe(3);
  expect(migrated.princesses[0].activity).toMatchObject({ elapsed: 1300, duration: 8500, activityId: 'meal' });
  expect(migrated.coins).toBe(10);
  expect(migrated.inventory.outfits).toEqual([]);
  await expect.poll(async () => (await savedMansion(page)).hearts, { timeout: 10000 }).toBe(2);
  expect((await savedMansion(page)).coins).toBe(14);
  await page.reload();
  await rendered(page);
  expect((await savedMansion(page)).hearts).toBe(2);
  expect((await savedMansion(page)).coins).toBe(14);
});

test('a rotated princess on the slide can be grabbed by her visible head and moved off the attraction', async ({ page }) => {
  const state = careFixture('playground');
  state.autonomyEnabled = false;
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await seedMansion(page, state);
  await readyMansion(page);
  await page.getByTestId('station-royal-slide').click();
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
  const base = roomIndex('playground') * ROOM_WIDTH;
  const head = await worldPoint(page, base + 292, 382);
  const emptyGround = await worldPoint(page, base + 492, 382);
  await page.mouse.move(head.x, head.y);
  await page.mouse.down();
  await page.mouse.move(emptyGround.x, emptyGround.y, { steps: 12 });
  await expect(page.getByTestId('mansion-game')).toHaveAttribute('data-moving', 'true');
  await page.mouse.up();
  await expect.poll(async () => (await savedMansion(page)).princesses[0].activity).toBeNull();
  expect((await savedMansion(page)).hearts).toBe(0);
});

test('failed invitation decisions remain pending and explicit retry invites exactly one princess', async ({ page }) => {
  const state = careFixture();
  state.hearts = 4;
  await seedMansion(page, state, { showInvitations: true });
  await readyMansion(page);
  const notice = page.getByRole('dialog', { name: 'Mira can join your family!' });
  await expect(notice).toBeVisible();
  await failSaveWrites(page);
  await notice.getByRole('button', { name: 'Invite now', exact: true }).click();
  await expect(page.getByRole('dialog', { name: "Let's protect your adventure" })).toBeVisible();
  expect((await savedMansion(page)).princesses).toHaveLength(1);
  expect((await savedMansion(page)).acknowledgedInvitationIds).not.toContain('mira');
  await page.evaluate(() => localStorage.setItem('mansion-simulate-quota', 'false'));
  await page.getByRole('button', { name: 'Try saving again', exact: true }).click();
  await expect(notice).toBeVisible();
  expect((await savedMansion(page)).princesses).toHaveLength(1);
  await notice.getByRole('button', { name: 'Invite now', exact: true }).click();
  await rendered(page, 'mansion');
  expect((await savedMansion(page)).princesses).toHaveLength(2);
  expect((await savedMansion(page)).acknowledgedInvitationIds).toContain('mira');
});

test('invitation notices defer behind instructions, queue individually, and Later persists', async ({ page }, testInfo) => {
  await trackAudio(page);
  const state = careFixture();
  state.hearts = 18;
  state.tutorialSeen = false;
  state.autonomyEnabled = false;
  await seedMansion(page, state, { showInvitations: true, muted: false });
  await readyMansion(page);
  await expect(page.getByRole('dialog')).toHaveCount(1);
  await expect(page.getByRole('dialog', { name: 'Mira can join your family!' })).toHaveCount(0);
  expect((await audioState(page)).played.filter(src => src.endsWith('fanfare.wav'))).toHaveLength(0);
  await page.getByRole('button', { name: /Got it! Let's Play!/ }).click();
  await expect(page.getByRole('dialog', { name: 'Mira can join your family!' })).toBeVisible();
  await expect.poll(async () => (await audioState(page)).played.filter(src => src.endsWith('fanfare.wav')).length).toBe(1);
  await page.screenshot({ path: testInfo.outputPath('mira-invitation.png') });
  await page.getByRole('button', { name: 'Later', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Coral can join your family!' })).toBeVisible();
  await expect.poll(async () => (await audioState(page)).played.filter(src => src.endsWith('fanfare.wav')).length).toBe(2);
  expect((await savedMansion(page)).princesses).toHaveLength(1);
  expect((await savedMansion(page)).acknowledgedInvitationIds).toContain('mira');
  await page.reload();
  await rendered(page);
  await expect(page.getByRole('dialog', { name: 'Coral can join your family!' })).toBeVisible();
  await page.getByRole('button', { name: 'Later', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Flora can join your family!' })).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(1);
});

test('the last individual invitation does not stack a second fanfare on collection celebration', async ({ page }) => {
  await trackAudio(page);
  let state = careFixture();
  state.hearts = 82;
  state.autonomyEnabled = false;
  for (const id of PRINCESS_IDS.slice(1, -1)) state = command(state, { type: 'invite', id }).state;
  await seedMansion(page, state, { showInvitations: true, muted: false });
  await readyMansion(page);
  await expect(page.getByRole('dialog', { name: 'Nova can join your family!' })).toBeVisible();
  await page.getByRole('button', { name: 'Invite now', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'A home full of friendship!' })).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(1);
  await expect.poll(async () => (await audioState(page)).played.filter(src => src.endsWith('fanfare.wav')).length).toBe(1);
  expect((await audioState(page)).contexts).toBeLessThanOrEqual(1);
  await page.getByRole('button', { name: 'Keep caring together', exact: false }).click();
  await rendered(page);
  expect((await savedMansion(page)).collectionCelebrated).toBe(true);
  await page.reload();
  await rendered(page);
  await expect(page.getByRole('dialog')).toHaveCount(0);
});

test('earning an invitation during a beach activity shows confetti and a fanfare without changing the trip', async ({ page }) => {
  await trackAudio(page);
  let state = careFixture('beach');
  state.hearts = 3;
  state.autonomyEnabled = false;
  state = command(state, { type: 'place', id: 'liora', room: 'beach', x: 280, y: 480, stationId: 'sandcastle-cove' }).state;
  state = advance(state, ACTIVITIES.sandcastle.duration - 1500).state;
  await seedMansion(page, state, { showInvitations: true, muted: false });
  await readyMansion(page);
  await page.getByRole('button', { name: 'Liora', exact: true }).click();
  const notice = page.getByRole('dialog', { name: 'Mira can join your family!' });
  await expect(notice).toBeVisible({ timeout: 5000 });
  await expect(notice).toContainText(en.princessMansion.awaitingAtHome);
  await expect(page.getByTestId('invitation-confetti').locator('i')).toHaveCount(36);
  await expect.poll(async () => (await audioState(page)).played.filter(src => src.endsWith('fanfare.wav')).length).toBe(1);
  expect((await savedMansion(page)).princesses).toHaveLength(1);
  await notice.getByRole('button', { name: 'Invite now', exact: true }).click();
  await rendered(page, 'beach');
  const invited = await savedMansion(page);
  expect(invited.hearts).toBe(4);
  expect(invited.trip?.companions).toEqual(['liora']);
  expect(invited.selectedId).toBe('liora');
  expect(invited.cameraRoom).toBe('beach');
  expect(invited.princesses.find(princess => princess.id === 'mira')?.room).toBe('dining');
  expect(invited.acknowledgedInvitationIds).toContain('mira');
});

test('beach ambience changes one existing loop and respects mute and home return', async ({ page }) => {
  await trackAudio(page);
  const state = careFixture();
  state.autonomyEnabled = false;
  await seedMansion(page, state);
  await readyMansion(page);
  await page.getByRole('button', { name: 'Sound Off', exact: true }).click();
  await expect.poll(async () => (await audioState(page)).ambient?.file).toBe('palace-ambient.wav');
  await page.getByRole('button', { name: 'Outings', exact: true }).click();
  await page.getByRole('radio', { name: 'Shellsong beach', exact: true }).check();
  await page.getByRole('button', { name: "Let's go!", exact: true }).click();
  await rendered(page, 'beach');
  await expect.poll(async () => (await audioState(page)).ambient?.file).toBe('beach-ambient.wav');
  await expect.poll(async () => (await audioState(page)).ambient?.paused).toBe(false);
  expect((await audioState(page)).ambientCount).toBe(1);
  expect((await audioState(page)).ambient?.volume).toBeLessThanOrEqual(0.15);
  await page.getByRole('button', { name: 'Sound On', exact: true }).click();
  await expect.poll(async () => (await audioState(page)).playing).toEqual([]);
  await page.getByRole('button', { name: 'Return home', exact: true }).click();
  await rendered(page, 'mansion');
  expect((await audioState(page)).ambientCount).toBe(1);
  expect((await audioState(page)).ambient?.file).toBe('palace-ambient.wav');
});

test('household autonomy settings stay locked on an outing and become editable after returning', async ({ page }) => {
  await seedMansion(page, careFixture('beach'));
  await readyMansion(page);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  const autonomy = page.getByRole('checkbox', { name: 'Lively princesses', exact: true });
  await expect(autonomy).toBeDisabled();
  await expect(autonomy).toBeChecked();
  await expect(autonomy).toHaveAccessibleDescription(en.princessMansion.autonomyAwayDescription);
  await expect(page.getByRole('checkbox', { name: 'Quiet adventure ambience', exact: true })).toBeEnabled();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Return home', exact: true }).click();
  await rendered(page, 'mansion');
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await expect(autonomy).toBeEnabled();
  await autonomy.uncheck();
  expect((await savedMansion(page)).autonomyEnabled).toBe(false);
});

for (const [locale, messages] of Object.entries({ en, he, zh, es })) {
  test(`${locale} has localized accessible mobile shopping, real purchases, and 48px controls`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.emulateMedia({ reducedMotion: 'reduce' });
    const state = careFixture();
    state.coins = 40;
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    await seedMansion(page, state);
    await readyMansion(page, locale);
    const copy = messages.princessMansion;
    await page.getByRole('button', { name: messages.common.instructions, exact: true }).click();
    const instructions = page.getByRole('dialog', { name: copy.instructionsTitle });
    const starterCards = instructions.getByRole('heading', { level: 3 }).first().locator('..');
    await expect(starterCards.getByRole('heading', { level: 4 })).toHaveCount(4);
    await expect(instructions.getByText(copy.instructions.shopping.title, { exact: true })).toHaveCount(0);
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: copy.travel, exact: true }).click();
    const travelHelp = page.getByTestId('help-trips');
    await travelHelp.getByRole('button').click();
    await expect(travelHelp.getByText(copy.instructions.trips.description, { exact: true })).toBeVisible();
    await page.getByRole('button', { name: copy.trip.depart, exact: true }).click();
    await rendered(page, 'mall');
    await page.getByTestId('shop-outfits').click();
    const dialog = page.getByRole('dialog', { name: copy.shopping.outfitsTitle });
    await expect(dialog).toBeVisible();
    const shoppingHelp = page.getByTestId('help-shopping');
    await shoppingHelp.getByRole('button').click();
    await expect(shoppingHelp.getByText(copy.instructions.shopping.description, { exact: true })).toBeVisible();
    const card = page.getByTestId('item-rose-gala');
    await card.getByRole('button', { name: copy.shopping.preview, exact: true }).click();
    const buy = card.getByRole('button', { name: copy.shopping.buy.replace('{price}', '18'), exact: true });
    expect((await buy.boundingBox())?.height).toBeGreaterThanOrEqual(48);
    await buy.click();
    expect((await savedMansion(page)).coins).toBe(22);
    await page.screenshot({ path: testInfo.outputPath(`mobile-boutique-${locale}.png`) });
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    if (locale === 'he') expect(await dialog.evaluate(element => getComputedStyle(element).direction)).toBe('rtl');
    expect(errors).toEqual([]);
  });
}

test('touch carries a princess onto the beach sandcastle attraction', async ({ browser }, testInfo) => {
  const context = await browser.newContext({ baseURL: testInfo.project.use.baseURL, viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const page = await context.newPage();
  try {
    const state = careFixture('beach');
    state.autonomyEnabled = false;
    state.princesses[0].x = 940;
    await seedMansion(page, state);
    await readyMansion(page);
    await page.locator('canvas').scrollIntoViewIfNeeded();
    const start = await worldPoint(page, 940, 390);
    const end = await worldPoint(page, 280, 390);
    const session = await context.newCDPSession(page);
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: start.x, y: start.y, id: 1 }] });
    for (let i = 1; i <= 12; i++) await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: start.x + (end.x - start.x) * i / 12, y: end.y, id: 1 }] });
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    await expect.poll(async () => (await savedMansion(page)).princesses[0].activity?.stationId).toBe('sandcastle-cove');
    await expect(page.locator('canvas')).toHaveCount(1);
  } finally { await context.close(); }
});
