# run-ralph-copilot.ps1 — Launcher for Ralph GSD (Copilot CLI)
# Generated by /ralph skill. Run from the ralph-copilot/ subdirectory.
param([switch]$Review, [switch]$SkipVerify)

$prdPath = Join-Path $PSScriptRoot "prd.json"
if (-not (Test-Path $prdPath)) { Write-Host "Error: prd.json not found in $PSScriptRoot" -ForegroundColor Red; exit 1 }

# Find the real ralph-copilot.ps1
$searchPaths = @(
    (Join-Path $env:USERPROFILE ".copilot\installed-plugins\agency-playground\ralph-gsd\ralph-copilot\ralph-copilot.ps1"),
    (Join-Path $PSScriptRoot "ralph-copilot.ps1")
)
$scriptPath = $searchPaths | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $scriptPath) {
    $found = Get-ChildItem -Path "$env:USERPROFILE\.claude\plugins" -Recurse -Filter "ralph-copilot.ps1" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($found) { $scriptPath = $found.FullName } else { Write-Host "Error: ralph-copilot.ps1 not found. Is the ralph-gsd plugin installed?" -ForegroundColor Red; exit 1 }
}

$params = @{ PrdPath = $prdPath }
if ($Review) { $params.Review = $true }
if ($SkipVerify) { $params.SkipVerify = $true }
& $scriptPath @params
